# Streamlit secrets configuration
# Copy this file to .streamlit/secrets.toml and add your API key

[general]
OPENROUTER_API_KEY = "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"
